[package]
name = "event_store_types"
version.workspace = true
edition.workspace = true

[dependencies]
candid.workspace = true
serde.workspace = true
serde_bytes.workspace = true
serde_json.workspace = true
serde_json.optional = true

[features]
json = ["serde_json"]