[workspace]
members = [
    "rs/canister/api",
    "rs/canister/impl",
    "rs/consumer",
    "rs/consumer/agent_runtime",
    "rs/consumer/cdk_runtime",
    "rs/producer",
    "rs/producer/agent_runtime",
    "rs/producer/cdk_runtime",
    "rs/integration_tests",
    "rs/types",
    "rs/utils",
]
resolver = "2"

[workspace.package]
version = "0.11.0"
edition = "2024"

[workspace.dependencies]
candid = "0.10.32"
ic-agent = "0.49.0"
ic-cdk = "0.20.2"
ic-cdk-management-canister = "0.1.1"
ic-cdk-timers = "1.0.0"
ic-http-certification = "3.2.0"
ic_principal = "0.1.5"
ic-stable-structures = "0.7.2"
pocket-ic = "15.0.0"
querystring = "1.1.0"
rand = "0.8.5"
rmp-serde = "1.3.1"
serde = "1.0.229"
serde_bytes = "0.11.19"
serde_json = "1.0.151"
sha2 = "0.11.0"
test-case = "3.3.1"
time = "0.3.54"
tokio = "1.53.0"
tokio-util = "0.7.18"
tracing = "0.1.44"
